### ISSUE TITLE
Dockerhub typo: integritee-node-dev pull cmd is the same as for the non-dev node.

### ISSUE THREAD

**Issue by clangenb** [scs/substraTEE-node#104]
![image](https://user-images.githubusercontent.com/37865735/146354701-01f27c7d-9791-4214-a221-2b46d09e0f97.png)

**Comment by mosonyi** [comment]
It is ok, just there's not enough space to show. Copy and paste to check.
![image](https://user-images.githubusercontent.com/6170620/148056784-b0779bb0-b915-49b6-a4ab-44a9f0a5da8b.png)
