### ISSUE TITLE
Multiple tcp connections at node

### ISSUE THREAD

**Issue by andyjsbell** [scs/substraTEE-node#116]
**Question**

It seems there are multiple connections being opened from the worker to the node.  Running the worker in software mode within a docker container and connecting to a node in another container I see the following rapidly repeated:

```
....
ajuna-node_1  | 2022-03-31 09:00:24 Accepted a new tcp connection from 172.19.0.3:56406.
ajuna-node_1  | 2022-03-31 09:00:24 Accepted a new tcp connection from 172.19.0.3:56408.
ajuna-node_1  | 2022-03-31 09:00:24 Accepted a new tcp connection from 172.19.0.3:56410.
ajuna-node_1  | 2022-03-31 09:00:24 Accepted a new tcp connection from 172.19.0.3:56412.
....
``` 

Is this intended?  It seems a waste of resources and a potential issue if we end up consuming all the file descriptors made available.

**Comment by haerdib** [comment]
I think that's a duplicate issue: https://github.com/scs/substrate-api-client/issues/133
It is not intended, but as it's a performance issue, we did not prioritize it yet.

**Comment by haerdib** [comment]
Closing this for now, because it's duplicate and not an issue on the node side.
