### ISSUE TITLE
make sudo a multisig account

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE-node#44]

**Comment by echevrier** [comment]
Create a multisig account in Genesis config (not as sudo)
Write tutorial for cases (from polkadot.js)
- transfer from multisig account 
- make multisig account as sudo and then test it with treasury

**Comment by echevrier** [comment]
_Tutorial_

### Multi-signature accounts
Multi-signature accounts cannot be modified after being created. Changing the set of members or altering the threshold is not possible and instead requires the dissolution of the current multi-sig and creation of a new one. As such, multi-sig account addresses are deterministic, i.e. you can always calculate the address of a multi-sig by knowing the members and the threshold, without the account existing yet.

A Multisig account is created in the genesis.  
- in the development config, the account contains Alice, Bob, Dave
- in the local testnet config, the account contains Alice, Bob, Charlie, Dave

To show up in polkadot.js the account has to be added:
- Click on +Multisig
- Select Signatories: Alice, Bob, Dave.
- Set threshold to 2

-> Multisig account with key 

> 2JSjRJ8Yban5FJjkLnCcV7hYpyqK6U9XQrhG1ze6ir7i8XRr

This account has a fund from the genesis like Alice account

**Note**: The address of a multi-signature account is deterministically generated from the signers and threshold of the multisig wallet. So the order of the adresses provided to the multi-sig account is important. 
Creating a multi-sig account from Polkadot-JS Apps UI, always sort the accounts according to the keys. For compatibilty reason, the multi-sig account created in the genesis config sort the account in the same way

### Scenarios

**1. Transfer 50 Unit from Multisig account to Eve from Accounts UI**

-  Generate extrinsic and first authorization (ex:Alice) 
    - Click on Send (Multisig account) and fill form
![Transfer_1](https://user-images.githubusercontent.com/84318241/135084914-84d114c2-a0ad-4418-a65a-2d5cc702905c.PNG)
    - Click Make Transfer
    ->authorize transaction form for first signature (Alice):
![authorization_alice](https://user-images.githubusercontent.com/84318241/135084953-4cdec78f-395b-4b08-8312-e58a10b20789.PNG)

    - Click Sign and Submit
    -> NewMultisig Event in block
![Event_1](https://user-images.githubusercontent.com/84318241/135085346-37e56051-4868-47b9-86a8-bcbe9c54d9d8.PNG)

    -> 1 Multisig approvals is pending. See Account UI
![1_approv_pending](https://user-images.githubusercontent.com/84318241/135081628-0bd4cc87-15c7-44f5-9811-a8e3fbc583e9.PNG)

- 2d authorization (ex:Dave): 
    - Click on Send (Multisig account) and fill form 
![Transfer_1](https://user-images.githubusercontent.com/84318241/135086064-13d9ef3b-c071-4d56-aef2-c063c8bbc95e.PNG)

    - Click Make Transfer
    -> authorize transaction form for second signature (ex:Dave):
     Note : the Multisig message with call (for final approval) is selected
![authorization_2d](https://user-images.githubusercontent.com/84318241/135086105-9516edfc-db8e-461f-b77a-bf4b881f8b5e.PNG)

    - Click Sign and Submit
    -> MultisigExecuted Event in block
![Event_Done](https://user-images.githubusercontent.com/84318241/135086291-fe97fd4b-4863-494f-8116-6b57cf0cef28.PNG)

    ->  Eve got 50 Unit and no multisig approval is pending anymore


**2. Transfer 50 Unit from Multisig  account to Charlie from Developer/extrinsics UI**
-  Go to Developer/extrinsics
-  Generate extrinsic and first authorization (ex:Bob) 
    - Using selected account: Multisig submit the following extrinsic
![Extrinsics_transfer_1](https://user-images.githubusercontent.com/84318241/135086901-bf491e89-de9f-4e06-8d0a-e7a066738ca0.PNG)

    - Click Submit Transaction 
    -> first authorization from Bob
![1-auth_extrinsics_bob](https://user-images.githubusercontent.com/84318241/135088306-e461b894-2b21-4f0b-a549-daa1db7146f1.PNG)

    - Click Sign and Submit
    -> NewMultisig Event in block
![Event_1_extrinsic](https://user-images.githubusercontent.com/84318241/135088406-c42ab85e-32a5-4606-8b91-70219062b56d.PNG)

- 2d authorization (ex:Dave): 
    - Change nothing extrinsics Submission UI
    - Click Submit Transaction
    -> authorize transaction form for second signature (ex:Dave):
     Note : the Multisig message with call (for final approval) is selected
![2-auth_extrinsics_dave](https://user-images.githubusercontent.com/84318241/135088500-cf5e4e3c-c6e5-4ab8-8d94-4ad11ec4126e.PNG)
    
    - Click Sign and Submit
    -> MultisigExecuted Event in block
    ->  Charlie got 50 Unit and no multisig approval is pending anymore



**3. Make Multisig account sudo**
- Go to Developer/Sudo
- submit following change sudo, setKey, new: Multisig
- Click Submit sudo
- Click Sign and Submit
-> Key_Changed Event in block 
![sudo_key_changed_event](https://user-images.githubusercontent.com/84318241/135092963-909e2235-9d49-48d9-a767-7b8438deacc1.PNG)
 
- Check the Sudo key:
    - Go to Developer/Chain state
    - Selected state query: sudo, key() ->  `2JSjRJ8Yban5FJjkLnCcV7hYpyqK6U9XQrhG1ze6ir7i8XRr`

**4. Treasury with sudo Multisig account**  
- Create a proposal from Eve (Eve needs fund): transfer 500 units to Ferdie
    - Go to Treasury Tab
    - Click Submit proposal
    - Fill Form according to desired proposal
    - Click Submit Proposal and Sign and Submit
    -> In the Treasury there is 1 proposal 
![proposal_1](https://user-images.githubusercontent.com/84318241/135090519-640e9648-54b5-453c-b63a-53d9666e6e4f.PNG)

- First accept of proposal (from ex Dave)
    -   Go to Developer/extrinsics and fill form
![1_approv_propos](https://user-images.githubusercontent.com/84318241/135090833-e2d517e9-5d7d-448c-bc80-35425bb262c5.PNG)

    - Click Submit Transaction
     -> first authorization from Dave
![1_approv_propos_authoriz](https://user-images.githubusercontent.com/84318241/135092399-bd63a4a2-976c-4d59-9dc7-4b25f8e83b31.PNG)

    - Click Sign and Submit
    -> NewMultisig Event in block
![1_approv_propos_event](https://user-images.githubusercontent.com/84318241/135092453-dfd1f3a1-333b-4365-a7b5-d788b6533223.PNG)

- 2d authorization (ex:Bob):
    - Change nothing extrinsics Submission UI
    - Click Submit Transaction
    -> authorize transaction form for second signature (Bob):  
    Note: the Multisig message with call (for final approval) is selected
![2_approv_propos_authoriz](https://user-images.githubusercontent.com/84318241/135092527-54309b79-1ee6-4f92-a818-e0ab06a138c6.PNG)

    - Click Sign and Submit
    -> MultisigExecuted Event in block
![2_approv_propos_event](https://user-images.githubusercontent.com/84318241/135092581-b4af1bd8-2acd-419f-835f-d063b2e3b9cc.PNG)

-> In the Treasury there is 1 approve proposal
![approved_proposal](https://user-images.githubusercontent.com/84318241/135092634-8c15d22b-e2ce-4876-8030-eded19dea2ec.PNG)

**Comment by brenzi** [comment]
`forceTransfer` should only work with sudo. Your screenshot confuses me as it should fail. should be `transfer` instead

Just reproduced: Your flow gets the multisig approved, but the dispatch will fail with `BadOrigin`. As to be expected.

**Comment by brenzi** [comment]
I actually think, the better instructions would be:
1. original author of multisig extrinsic copy-pastes the `encoded call data` and `encoded call hash` and sends that to the others. 
2. The others check pending multisig approvals in the js/apps UI and select "..." -> "Multisig Approvals" where they just enter the call data and do not need to re-enter all extrinsic data (important because it may even be a batch of 999 extrinsics ....

Tested changing sudo as well and then doing a forceTransfer. all works as expected

Now I understood: The first multisig extrinsic doesn't actually send the extrinsic it wants to execute to the chain at all. It just registers its hash. The others approve the hash and have to check for themselves if the hash corresponds to what they think will be executed. Only the final approval actually submits the extrinsic and it gets executed
