### ISSUE TITLE
Add Proxy Pallet

### ISSUE THREAD

**Issue by echevrier** [scs/substraTEE-node#49]
Add Pallet to allow users to set proxy accounts to perform a limited number of actions on their behalf
For now, set it up as in Kusama.

**Comment by echevrier** [comment]
Difference from Kusama :
the available ProxyType are

- Any, which allows any transaction
- NonTransfer, that allow any type of transaction except balance transfers (including vested transfers)
- Governance,  that allow any transactions related to governance. In our case only Treasury. 
- CancelProxy.

In Kusama are also possible proxy for Staking, IdentityJudgement and Auction. I haven't added them as we don't have such functionalities. 

Question: does the Governance type make sense in our case. It allows for now only Treasury calls

**Comment by echevrier** [comment]
### Tutorial / Test
**Polkadot.js**
To use it with Polkadot.js, you need to provide the ProxyType definition -> Add to Settings/developer:
```
"ProxyType": {
 "_enum": ["Any", "NonTransfer", "Governance", "CancelProxy"]
 },
```
**1. Set up a Any proxy: Eve will be a proxy account of Alice**

- Transfer 1000 Unit from Alice to Eve
- Go to Developer/extrinsics
- Select the primary account (President) Alice
- Choose proxy pallet and addProxy method
    - Proxy_type: Any
    - Select proxy account, the account that has the proxy on it (Minister) Eve, Ferdie
- Click Submit Transaction
- Click Sign and Submit

-> The proxy has been created :

- Check Event in block :

![Add_proxy_event_1](https://user-images.githubusercontent.com/84318241/135295843-bcfa1653-afb9-4ab2-aec2-21eccbccc301.PNG)

- Check the chain state:
    - Go to Developer/Chain state
    - Select state query: proxy, proxies. AccountId Alice
    
![proxy_alice_1](https://user-images.githubusercontent.com/84318241/135296185-0a5cf327-ee21-4659-9c95-c61b4d75115f.PNG)


**2. Transfer money using the created proxy**

- Click Send from Alice account
    - Send to adresse: choose Ferdie
    - Amount: 100
    - Click Make Transfer
-> authorize transaction form : 

![authorize_proxy_transfer](https://user-images.githubusercontent.com/84318241/135296515-4870cb14-d79e-4afc-ad92-8310cea96b00.PNG)

- Click Sign and Submit

-> The transfer has been executed:

Check the block :   
![transfer_executed](https://user-images.githubusercontent.com/84318241/135296982-2a307dd8-40dc-4a03-9b16-2baf9843c39e.PNG)


Check the account balances: Eve 999.996, Ferdie : 100, Alice 1.1518 MUNIT (100 were removed from Alice account)

**3. Anonymous Proxies**
**NOTE**: The account that creates the proxy relationship is the proxy account and the new account is the primary. Use extreme care with anonymous proxies; once you remove the proxy relationship, the account will be inaccessible.

**NOTE**: The first anonymous proxy you add should always be of type Any. Also, if there are multiple anonymous proxies for the proxied account, you should keep at least one Any type. Without having an Any type proxy, you won't be able to send funds, add new proxies, kill the anonymous proxy or take any action not specifically allowed by the types of the proxies the account has.

**4. Create an anonymous Proxies**

- Go to Developer/extrinsics
- Select the primary account Bob
- Choose proxy pallet and anonymous method
    - Proxy_type: Any
- Click Submit Transaction

-> The proxy has been created :

- Check Event in block and **remember the event block height !!!**
![Bob_Anonymous_Created](https://user-images.githubusercontent.com/84318241/135304935-8e924854-d77a-4d99-9d21-a25ff27e760e.PNG)

- Check the chain state:
    - Go to Developer/Chain state
    - Select state query: proxy, proxies. No AccountId option selected : 
   
![Bob_Ano_Chain_state](https://user-images.githubusercontent.com/84318241/135305300-66039540-5785-4493-a3ca-b1c8bf51d1eb.PNG)

 
**4. Add the anonymous Proxy as an account to Polkadot-JS accounts**
- Go to Accounts
- Click Proxied
    - Set the proxy address : here : 2PhGJeXzXuawxNszdGEPW8EMCD1SvYSpohGsvaUyBBGjGuX3
    - Set Name : Anonym to Bob
- Click Add
-> The proxied Anonym To Bob is listed

**5. Transfer from Anonymous account**

- Send funds from Bob to Anonym to Bob : 5000
- Click Send of Anonym to Bob
    - Send to adress Ferdie, Amount 100
- Click Make Transfer

-> authorize transaction form

![authorize_anonym_transfer](https://user-images.githubusercontent.com/84318241/135306022-64e8d922-8c7a-493d-8117-562112fd9e4c.PNG)

- Click Sign and Submit

-> The transfer has been executed:
- Check Balances: Ferdie has 100, Anonym to Bob has 4900

**6. Remove Anonymous proxy** _Doesn't work_ 
- Go to Developer/extrinsics
- Select the  account Anonym to Bob
- Choose proxy pallet and killAnonymous method
    - Spawner: original account : Alice
    - Proxy_type: Any
    - Index: 0
    - Block number: the block number of its creation. Here : 395
- Click Submit Transaction and SIgn and Submit

-> Error : Call may not be made by proxy because it may escalate its privileges.

**7. Permissionless management**
....

**Comment by brenzi** [comment]
we manly need "any", but your choice makes sense as is

The tutoeial would be more meaningful if the anon proxy is an account without corresponding private key, so we never want to make Eve an anon proxy of bob...
