### ISSUE TITLE
repeat benchamrk on the DO droplet

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE-node#65]

**Comment by brenzi** [comment]
and commit the results to the GH repo

**Comment by brenzi** [comment]
@clangenb plz point to instructions to run benchmark

**Comment by clangenb** [comment]
* Instructions apply for after #66 has been merged.

1. The node must be compiled with: `cargo build --release --features runtime-benchmarks`
2. Run: `./scripts/benchmark_all_pallets.sh <path-to-node-bin> integritee-solo-fresh <path-to-output-files>`

If the script is run from the repo's root directory, all arguments can be omitted and the output weight files will be at the correct location.
