### ISSUE TITLE
upgrade teerex

### ISSUE THREAD

**Issue by brenzi** [scs/substraTEE-node#74]
to include latest security fixes

**Comment by brenzi** [comment]
do integritee-network/pallet-teerex#54 first

**Comment by mosonyi** [comment]
@haerdib please clarify with @brenzi

**Comment by haerdib** [comment]
@brenzi - which secruity issues should be fixed here?

**Comment by brenzi** [comment]
They have been fixed by Edith. we just need to upgrade to teerex master. that's all
