### ISSUE TITLE
How can I test transfer TEER?

### ISSUE THREAD

**Issue by Wangmmx** [scs/substraTEE-node#78]
Hello, I am working on wallet app development need to  test TEER transfer. I found a public ws node and configured, and tried to send a transaction, but the broadcast error reported that the balance was insufficient. What if I get test coins? In addition, I have a few questions:
1. Has the integritee mainnet opened? I see only the genesis block, is there a relevant time point?
2. Is there a testnet and test currency for reference？
3. The interface to get the nonce is now reporting an error. This is Polkadot's public interface`system_accountNextIndex`. Doesn't it support Polkadot related RPC operations?
Thanks a lot!

**Comment by brenzi** [comment]
Dear @Wangmmx. Thanks for building a wallet with TEER support. You did likely find the right node for our parachain node but as we're not a parachain just yet, you won't be able to do transactions.
Moreover, you need some initial funds to be able to pay fees to send a transaction.

We currently have no public testnet, but what you can do is:
download and run our latest release locally `integritee-node --dev` and test against that.

As we support exactly the same json rpc as Polkadot, you can rest assured that the changes for basic TEER support are mainly changing the public rpc node.

**Comment by Wangmmx** [comment]
Thank you for your patient reply! Then I will wait for integrintee to become a parachain and then test the transfer function, looking forward to the next upgrade, thanks again
