### ISSUE TITLE
init.sh script not working

### ISSUE THREAD

**Issue by haerdib** [scs/substraTEE-node#80]
Currently,  the script [init.sh](https://github.com/integritee-network/integritee-node/blob/master/scripts/init.sh) is not working because we removed the `rust-toolchain` file. We should either remove it completely (as it has been replaced by https://github.com/integritee-network/integritee-node/blob/master/ci/install_rust.sh I believe?) or fix it.

**Comment by brenzi** [comment]
I think tha new rust toolchain toml solves the installing of the wasm32 target, so we won't need that file anymore

**Comment by clangenb** [comment]
Yes, not needed anymore, if rust is installed already.
